disabled_rules: # rule identifiers to exclude from running
  - force_cast
  - function_body_length
  - leading_whitespace
  - trailing_whitespace
  - vertical_whitespace
  - line_length
  - cyclomatic_complexity
  - mark
  - function_parameter_count
  - type_body_length
  - unused_optional_binding
opt_in_rules: # some rules are only opt-in
  # - empty_count
  # - missing_docs
  # Find all the available rules by running:
  # swiftlint rules
  - force_unwrapping
  - closing_brace
  - closure_end_indentation
  - closure_spacing
  - operator_usage_whitespace
  - private_outlet
  - sorted_imports
  - switch_case_on_newline
included: # paths to include during linting. `--path` is ignored if present.
  - SafeDrive
  - Service
  - Shared
  - Finder
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods
  - SafeDriveTests
